services:
    api:
      container_name: fofoprono-api
      image: ghcr.io/chomeirb/fofoprono-server:main
      depends_on:
        - db
      environment:
        - DATABASE_URL
        - POSTGRES_PASSWORD
        - PORT=${API_PORT}
        - DOMAIN
        - COOKIE_DOMAIN
        - API_URL
        - SMTP_HOST
        - SMTP_USERNAME
        - SMTP_PASSWORD
        - MAINTAINER_MAIL
        - COOKEY
      ports:
        - ${API_PORT}:${API_PORT}