services:
    api-dev:
      container_name: fofoprono-api-dev
      image: ${IMAGE}
      depends_on:
        - db-dev
      environment:
        - DATABASE_URL
        - POSTGRES_PASSWORD
        - PORT=${API_PORT}
        - DOMAIN
        - COOKIE_DOMAIN=${DOMAIN}
        - API_URL
        - SMTP_HOST
        - SMTP_USERNAME
        - SMTP_PASSWORD
        - MAINTAINER_MAIL
        - COOKEY
      ports:
        - ${API_PORT}:${API_PORT}
