services:
    api:
      container_name: fofoprono-api
      image: ghcr.io/chomeirb/fofoprono-server:main
      depends_on:
        - db
      environment:
        - DATABASE_URL
        - POSTGRES_PASSWORD
        - PORT=${API_PORT}
        - DOMAIN
        - API_URL
        - MAIL_USERNAME
        - MAIL_PASSWORD
        - COOKEY
      ports:
        - ${API_PORT}:${API_PORT}
  
    db:
      container_name: fofoprono-db
      image: postgres:14-alpine
      environment:
        - POSTGRES_PASSWORD
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgresql/data

volumes:
  db-data:
