services:
    api-dev:
      container_name: fofoprono-api-dev
      image: ${IMAGE}
      depends_on:
        - db-dev
      environment:
        - DATABASE_URL
        - POSTGRES_PASSWORD
        - PORT=${API_PORT}
        - DOMAIN
        - API_URL
        - MAIL_USERNAME
        - MAIL_PASSWORD
        - COOKEY
      ports:
        - ${API_PORT}:${API_PORT}
  
    db-dev:
      container_name: fofoprono-db-dev
      image: postgres:14-alpine
      environment:
        - POSTGRES_PASSWORD
      ports:
        - 5433:5432
      volumes:
        - ./db-data:/var/lib/postgresql/data
  