services:
  api:
    container_name: fofoprono-api
    image: ${IMAGE}
    ports:
      - ${API_PORT}:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL
      - POSTGRES_PASSWORD
      - PORT=${API_PORT}
      - DOMAIN
      - API_URL
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - COOKEY

  db:
    container_name: fofoprono-postgresql
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
